sudo: required

language: go
go:
- "1.11"

env:
- GO111MODULE=on

services:
- docker

before_install:
- go get -u github.com/mattn/goveralls

install:
- git fetch origin +refs/heads/*:refs/remotes/origin/*

script:
- ./build/travis.sh
