sudo: required

language: go
go:
- "1.10"

services:
- docker

install:
- git fetch origin +refs/heads/*:refs/remotes/origin/*

before_install:
- go get -u github.com/mattn/goveralls github.com/golang/dep/cmd/dep

script:
- ./build/travis.sh
